{{- if .Values.crds.create -}}
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: resourceclaims.{{ include "poolboy.operatorDomain" . }}
spec:
  group: {{ include "poolboy.operatorDomain" . }}
  version: v1
  scope: Namespaced
  names:
    plural: resourceclaims
    singular: resourceclaim
    kind: ResourceClaim
    shortNames: []
  subresources:
    status: {}
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: resourcehandles.{{ include "poolboy.operatorDomain" . }}
spec:
  group: {{ include "poolboy.operatorDomain" . }}
  version: v1
  scope: Namespaced
  names:
    plural: resourcehandles
    singular: resourcehandle
    kind: ResourceHandle
    shortNames: []
  subresources:
    status: {}
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: resourcepools.{{ include "poolboy.operatorDomain" . }}
spec:
  group: {{ include "poolboy.operatorDomain" . }}
  version: v1
  scope: Namespaced
  names:
    plural: resourcepools
    singular: resourcepool
    kind: ResourcePool
    shortNames: []
  subresources:
    status: {}
{{- end -}}
