apiVersion: v1
kind: Service
metadata:
  name: {{ include "poolboy.name" . }}
  namespace: {{ include "poolboy.namespaceName" . }}
  labels:
    {{- include "poolboy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.ports }}
  ports:
    {{- toYaml . | nindent 2 }}
  {{- end }}
  selector:
    {{- include "poolboy.selectorLabels" . | nindent 4 }}
  sessionAffinity: None
