---
name: poolboy-publish-to-quay
on:
  push:
    branches-ignore:
    - '*'
    tags:
    - 'v[0-9]*'
jobs:
  build:
    if: github.repository == 'redhat-cop/poolboy'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
    - name: Publish My Image to Quay
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: redhat-cop/poolboy
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}
        registry: quay.io
        context: operator
        dockerfile: operator/Dockerfile
        tags: ${{ steps.get_version.outputs.VERSION }},latest
